version: '2'
services:
  db:
    container_name: mongo-db
    ports:
      - 27017:27017
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - company-network
  review-service:
    container_name: review-service
    build:
      context: review-service
      dockerfile: Dockerfile
    image: review-service:latest
    ports:
      - 18888:8888
    networks:
      - company-network
    restart: always
  product-service:
    container_name: product-service
    build:
      context: product-service
      dockerfile: Dockerfile
    image: product-service:latest
    ports:
      - 19999:9999
    networks:
      - company-network
    restart: on-failure
networks:
  company-network:
    driver: bridge