version: '2'
services:
  db:
    ports:
      - 27017:27017
    image: mongo:latest
    volumes:
      - ./data:/data/db
      - ./seed:/seed
    networks:
      - drifter-network
  review-service:
    build:
      context: review-service
      dockerfile: Dockerfile
    image: review-service:${REVIEW_VERSION}
    ports:
      - "9001-9010:80"
    depends_on:
      - db
    networks:
      - drifter-network
  product-service:
    build:
      context: product-service
      dockerfile: Dockerfile
    image: product-service:${PRODUCT_VERSION}
    ports:
      - "9011-9020:80"
    depends_on:
      - db
    networks:
      - drifter-network
networks:
  drifter-network:
    driver: bridge