version: '2'
services:
  db:
    container_name: db
    ports:
      - 27017:27017
    image: mongo:latest
    volumes:
      - ./data:/data/db
      - ./seed:/seed
    networks:
      - drifter-network
  review-service:
    container_name: review-service
    build:
      context: review-service
      dockerfile: Dockerfile
    image: review-service:${REVIEW_VERSION}
    ports:
      - 9001:80
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
    networks:
      - drifter-network
  product-service:
    container_name: product-service
    build:
      context: product-service
      dockerfile: Dockerfile
    image: product-service:${PRODUCT_VERSION}
    ports:
      - 9002:80
    environment:
      - DRIFTER_REVIEW_URL=${REVIEW_SERVICE}
    networks:
      - drifter-network
networks:
  drifter-network:
    driver: bridge